### ISSUE TITLE
`.godot` directory shouldn't be in git

### ISSUE THREAD

**Issue by vmedea** [TreacherousDev/Treacherous#3]
The `.godot` hidden directory [contains cached state](https://docs.godotengine.org/en/stable/tutorials/best_practices/version_control_systems.html#files-to-exclude-from-vcs) for the godot instance, there's no point committing it to git it will only waste storage space and generate potential merge conflicts.

**Comment by TreacherousDev** [comment]
thanks for the head's up - will fix it shortly.
